name: Deploy QA Back Telemed EHR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: choice
        default: 'testing'
        options:
          - testing
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    env:
      ZAMBDAS_LOCATION: packages/telemed-ehr/zambdas

    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Create the .env directory
        run: mkdir -p ${{ env.ZAMBDAS_LOCATION }}/.env/

      - name: Conditionally create empty development.json file
          if: ${{ github.event.inputs.environment != 'development' }}
          run: touch ${{ env.ZAMBDAS_LOCATION }}/.env/development.json

      - name: Conditionally create empty testing.json file
          if: ${{ github.event.inputs.environment != 'testing' }}
          run: touch ${{ env.ZAMBDAS_LOCATION }}/.env/testing.json

      - name: Create .env/${{ github.event.inputs.environment }}.json file
        run: |
          echo AUTH0_ENDPOINT=https://auth.zapehr.com/oauth/token >> ${{ env.ZAMBDAS_LOCATION }}/.env/${{ github.event.inputs.environment }}.json

      - name: Copy env file to local.json to support serverless package command
        run: cp ${{ env.ZAMBDAS_LOCATION }}/.env/${{ github.event.inputs.environment }}.json ${{ env.ZAMBDAS_LOCATION }}/.env/local.json

      - name: Install dependencies
        run: pnpm install

      - name: Setup zapehr secrets
        run: cd ${{ env.ZAMBDAS_LOCATION }} && pnpm setup-zapehr-secrets ${{ github.event.inputs.environment }}

      - name: Deploy zambdas
        run: cd ${{ env.ZAMBDAS_LOCATION }} && pnpm deploy-zambdas ${{ github.event.inputs.environment }}
